Un-comment all lines about intake pivot motor
FRCTeam3255/2024_Robot_Code pull request #146
Opened 2024-02-17 23:48 UTC by Hyrumthehotscott

Issue #114

2024-02-18 01:51 UTC, TaylerUva commented
Wait to merge this in until bot is build but looks good

2024-02-24 00:51 UTC, TaylerUva requested changes

2024-02-24 00:51 UTC, TaylerUva commented on src/main/java/frc/robot/subsystems/Intake.java
> +  CANSparkMax rightCenteringMotor;
These don't exist anymore

2024-02-24 00:51 UTC, TaylerUva commented on src/main/java/frc/robot/RobotMap.java
> +    public static final int INTAKE_RIGHT_CENTERING_MOTOR_CAN = 26;
these don't exist anymore

2024-02-24 04:03 UTC, closed without merging

2024-02-24 05:35 UTC, Hyrumthehotscott commented
😢