Add turret current limiting🦟™️
FRCTeam3255/2024_Robot_Code pull request #150
Opened 2024-02-19 21:58 UTC by BrodyKarr

2024-02-22 15:58 UTC, TaylerUva submitted a review, later dismissed

2024-02-23 02:17 UTC, TaylerUva requested changes

2024-02-23 02:17 UTC, TaylerUva commented on src/main/java/frc/robot/subsystems/Turret.java
> +    turretConfig.SoftwareLimitSwitch.ReverseSoftLimitEnable = false;
These need to be set back to true

2024-02-23 08:43 UTC, ACat701 commented
@TaylerUva  This can be merged in if we're fine with it not addressing #156

2024-02-23 08:46 UTC, TaylerUva approved these changes

2024-02-23 08:46 UTC, merged