made Transfer check if ready to shoot🦟™️
FRCTeam3255/2024_Robot_Code pull request #176
Opened 2024-02-24 19:42 UTC by BrodyKarr

2024-02-24 20:16 UTC, TaylerUva requested changes

2024-02-24 20:16 UTC, TaylerUva commented on src/main/java/frc/robot/commands/Shoot.java
> +    this.subTurret = subTurret;
Remove

2024-02-24 20:17 UTC, TaylerUva requested changes, later dismissed

2024-02-24 20:17 UTC, TaylerUva commented on src/main/java/frc/robot/commands/TransferGamePiece.java
>      globalTransfer.setTransferMotorSpeed(prefTransfer.transferMotorSpeed.getValue());
These will always run

2024-02-25 08:48 UTC, ACat701 commented
Closes #167 
Closes #173

2024-02-25 09:01 UTC, ACat701 commented
@TaylerUva  do we want this in main or do we want to wait until we fix the absolute encoders? Also, what's our plan from there? Vision? I just want to have a clear picture of how Tuesday should go. Unfortunately, I think we only have one meeting left for anything software so we really gotta make it count 🤞

Stuff we need to do:
- Abs Encoders
- Vision testing
- Auto (tuning, testing)
- Amp preset a bit better
- Trap attempted 
- Subwoofer preset a bit better
- Further testing with auto-aim (once Vision is working)
- Driver snapping to source and chain (once Vision is working, not as bad as it sounds)

I'm thinking
Fix Abs Encoders -> Vision testing -> Subwoofer -> Amp -> Driver snapping -> Trap (very temporarily) -> Auto for the rest of our time

I really think i am forgetting something

2024-02-25 09:08 UTC, TaylerUva commented
Let's merge this in and fix in main.

My suggestion:

1. Fix Abs Encoders (must do)
2. Vision testing (must do)
3. Trap functionality (1 hour)
4. Auto functionality (let's get a least one working)
5. Subwoofer (good enough already)
6. Amp (good enough already)
7. Driver snapping (🤷)

2024-02-25 09:35 UTC, TaylerUva approved these changes

2024-02-25 09:35 UTC, TaylerUva commented on src/main/java/frc/robot/subsystems/Transfer.java
> +    if ((feederMotor.getStatorCurrent() < -10) && (curVelocity < 0.8) && (current > 6) || hasGamePiece) {
These need to be made into preferences (in another PR)

2024-02-25 09:46 UTC, TaylerUva commented
Good to merge @ACat701? I approve

2024-02-26 00:05 UTC, merged