Shooter intake game piece detection 🦟™️
FRCTeam3255/2024_Robot_Code pull request #215
Opened 2024-03-09 18:30 UTC by BrodyKarr

2024-03-09 19:09 UTC, TaylerUva requested changes

2024-03-09 19:09 UTC, TaylerUva commented on src/main/java/frc/robot/RobotPreferences.java
> +        "intakeHasGamePieceCurrent", 7);
Can you add name intakeSource to make it more clear

2024-03-09 21:41 UTC, TaylerUva requested changes

2024-03-09 21:41 UTC, TaylerUva commented on src/main/java/frc/robot/subsystems/Intake.java
> +  public boolean intakeGamePieceDetection() {
Rename this to intakeSource...()

2024-03-09 21:41 UTC, TaylerUva commented on src/main/java/frc/robot/subsystems/Transfer.java
> +        (feederCurrent >= prefTransfer.feederHasGamePieceCurrent.getValue())
Why are we changing this? This will break ground intaking

2024-03-09 21:41 UTC, TaylerUva commented on src/main/java/frc/robot/commands/IntakeFromSource.java
> +      Climber subClimber, Intake subIntake) {
Does this end?

2024-03-14 23:40 UTC, ACat701 submitted a review, later dismissed

2024-03-14 23:40 UTC, ACat701 commented on src/main/java/frc/robot/subsystems/Intake.java
> +import frc.robot.RobotPreferences.prefIntake;
Remove all of your changes to Intake.java

2024-03-14 23:40 UTC, ACat701 commented on src/main/java/frc/robot/subsystems/Transfer.java
> +
We should still check the current of the feeder

2024-03-14 23:40 UTC, ACat701 commented on src/main/java/frc/robot/commands/IntakeFromSource.java
> +
end is missing some things here. (ex. Reposition game piece)
Please update your branch with main and refer to IntakeGroundGamePiece for what's missing

2024-03-14 23:40 UTC, ACat701 commented on src/main/java/frc/robot/RobotPreferences.java
> +     * The time that we wait to get a game piece in auto
Why was this added?

2024-03-15 00:32 UTC, ACat701 commented
The PID is HORRIBLE when running at such a low speed but its functional

2024-03-15 00:46 UTC, TaylerUva approved these changes

2024-03-15 00:59 UTC, TaylerUva approved these changes

2024-03-15 01:08 UTC, merged