changed all instances of pitch to hood🦟™️
FRCTeam3255/2024_Robot_Code pull request #221
Opened 2024-03-09 21:42 UTC by BrodyKarr

2024-03-10 05:33 UTC, TaylerUva requested changes
There are now merge conflicts as well

2024-03-10 05:33 UTC, TaylerUva commented on src/main/java/frc/robot/Constants.java
> +    public static final Transform3d ROBOT_TO_Hood = new Transform3d(
Constants should be all caps

2024-03-10 19:45 UTC, ACat701 requested changes

2024-03-10 19:45 UTC, ACat701 commented on src/main/java/frc/robot/RobotPreferences.java
>       * The elapsed time required to consider the pivot motor as zeroed
PIVOT!!!!!!!! 🚨🚨🚨🚨

2024-03-10 19:45 UTC, ACat701 commented on src/main/java/frc/robot/commands/ManualHoodMovement.java
> +    this.subHood = subhood;
subHood should be uppercase (make the H capitalized)

2024-03-10 19:45 UTC, ACat701 commented on src/main/java/frc/robot/subsystems/Hood.java
> +    SmartDashboard.putNumber("hood/Velocity DPS", getHoodVelocity());
All of these keys should be Hood/  not hood/

2024-03-13 04:30 UTC, TaylerUva commented
Too stale :(

2024-03-13 04:30 UTC, closed without merging