Create additional presets
FRCTeam3255/2024_Robot_Code pull request #259
Opened 2024-03-18 21:40 UTC by Alenguye582

2024-03-18 22:45 UTC, TaylerUva requested changes

2024-03-18 22:45 UTC, TaylerUva commented on src/main/java/frc/robot/commands/ShootingPreset.java
> +    subShooter.setIgnoreFlywheelSpeed(ignoreFlywheelSpeed);
These should all be done in initialize and we need to run shooter.getuptospeed

2024-03-18 22:45 UTC, TaylerUva commented on src/main/java/frc/robot/commands/ShootingPreset.java
> +    subShooter.setIgnoreFlywheelSpeed(ignoreFlywheelSpeed);
Don't forget to set it back to normal in end

2024-03-19 08:00 UTC, ACat701 commented
![image](https://github.com/FRCTeam3255/2024_Robot_Code/assets/90939494/f356a430-eaf9-4c17-aec9-1365ff6e3417)

2024-03-19 08:19 UTC, ACat701 commented
as much as we need to rename the gulf of Mexico, you all must understand that i have 2 days to learn these controls and i will not be physically capable of forgetting "gulf of Mexico" unless the new name is even funnier. this is very difficult task but we must over come it

2024-03-19 23:56 UTC, Alenguye582 commented
good news: the presets are presetting and Alice did not explode the robot by changing the button mapping 🎉

2024-03-20 00:07 UTC, TaylerUva approved these changes

2024-03-20 00:07 UTC, merged