Lock feeder to only feed ar goal rpm and angles
FRCTeam3255/2024_Robot_Code pull request #97
Opened 2024-02-09 01:44 UTC by dunep

2024-02-10 15:31 UTC, TaylerUva requested changes

2024-02-10 15:31 UTC, TaylerUva commented on src/main/java/frc/robot/commands/Shoot.java
> +    this.rightShooterFeedForward = rightShooterFeedForward;
You are close but missing something

2024-02-16 21:41 UTC, dunep commented
Issue #125

2024-02-18 10:21 UTC, TaylerUva requested changes

2024-02-18 10:21 UTC, TaylerUva commented on src/main/java/frc/robot/subsystems/Shooter.java
> +    leftMotorGoalSpeed = leftVelocity;
Is this being used for anything?

2024-02-18 10:21 UTC, TaylerUva commented on src/main/java/frc/robot/commands/Shoot.java
> +      SmartDashboard.putBoolean("At velocity", false);
This can be removed (only used for testing)

2024-02-18 10:21 UTC, TaylerUva commented on src/main/java/frc/robot/commands/Shoot.java
> +    SmartDashboard.putBoolean("At velocity", false);
This can be removed (only used for testing)

2024-02-18 10:21 UTC, TaylerUva commented on src/main/java/frc/robot/RobotPreferences.java
> +    public static final SN_DoublePreference pitchShooterD = new SN_DoublePreference("pitchShooterD", 0);
What are these used for?

2024-02-18 10:21 UTC, TaylerUva commented on src/main/java/frc/robot/RobotContainer.java
> +
These are needed anymore as we have the below function

2024-02-21 19:55 UTC, ACat701 requested changes

2024-02-21 19:55 UTC, ACat701 commented on src/main/java/frc/robot/RobotContainer.java
> +    DriverStation.silenceJoystickConnectionWarning(Constants.constRobot.SILENCE_JOYSTICK_WARNINGS);
The data is already being logged in Robot.java. Please remove this

2024-02-21 19:55 UTC, ACat701 commented on src/main/java/frc/robot/commands/Shoot.java
> +        && subShooter.isRightShooterAtVelocity(rightShooterVelocity.getValue(),
This currently only checks if our flywheels are up to speed. The name of this pr suggests that we would also like to check if our Pitch angle (and turret angle?) are also within tolerance. Either change the name of the pr or add a check for those angles.

2024-02-22 16:03 UTC, TaylerUva commented
Closing PR as it's too stale

2024-02-22 16:03 UTC, closed without merging